/*
--------------------------------------------------------------------------------
sales_breakdown
purpose:
    - calculates average production costs per category
    - summarizes total revenue by category
    - identifies revenue generated by individual customers
    - tracks volume of items sold by country
--------------------------------------------------------------------------------
*/

--avg costs in each category
select category_name,avg(production_cost) as avg_productions_cost
from gold.dim_products
group by category_name
order by avg_productions_cost desc;

--total revenue for each category
select p.category_name, sum(s.sales_amount) as total_revenue 
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.category_name
order by total_revenue;

--total revenue genereated by each customer
select 
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(sales_amount) revenue_by_customer
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by 
    c.customer_key,
    c.first_name,
    c.last_name
order by revenue_by_customer desc;

--total orders within each country
select 
    c.country,
    sum(s.quantity) items_by_country
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by 
    c.country
order by items_by_country desc;